### ISSUE TITLE
Edit event date from the calendar

### ISSUE THREAD

**Issue by dhrsta** [wernerjoss/wp-ics-importer#1]
Hello, could you help me to make the calendar edit dates and events that come from other calendars? link .ics
I attached images of what I would need.
Thank you
Atte
Marcelo
![index 14](https://user-images.githubusercontent.com/52534630/60665890-15a6f380-9e3c-11e9-96c4-5de68e92d680.jpg)
![index 13](https://user-images.githubusercontent.com/52534630/60665891-15a6f380-9e3c-11e9-8ba2-3b4b96914131.jpg)

**Comment by wernerjoss** [comment]
Hi Marcelo,
no, unfortunately not, as this plugin is not intended to edit any values from imported calendars.
you will have to edit the ics files beforehand.
