### ISSUE TITLE
Import into Events Manager

### ISSUE THREAD

**Issue by 360fun** [wernerjoss/wp-ics-importer#2]
Hi! 😃  Would be great if this plug-in could work together with Events Manager (https://wordpress.org/plugins/events-manager/) importing the events into the db! 😄

**Comment by wernerjoss** [comment]
well, this is not the intention of this plugin 😄

**Comment by 360fun** [comment]
so you don't find useful to manage the events after the import with a plugin-in like Events Manager?

**Comment by wernerjoss** [comment]
I'm not saying that would not be useful - it is just not the intention of this plugin, although its name is ...ics-importer.
the only purpose of it is to display a nice calendar from the data of one or more ics calendar(s).
what you propose, would be much more an extension of events-manager.
maybe you can ask there.
