### ISSUE TITLE
Problem with repeating events

### ISSUE THREAD

**Issue by norgey** [wernerjoss/wp-ics-importer#3]
Hi Werner,
i add a reapeating event in my nextcloud calendar, but in your wp-ics-importer this event never stops. In the ICS-Calendar plugin there is no problem with this event, so i think it is not a bug in nextcloud. Can you have a look at it?
Thank you!
I can provide you access to my nextcloud if necessary.

Greetings,
Jonas

**Comment by wernerjoss** [comment]
Hi Jonas,
sorry for the late answer.
unfortunately, I don't think I will investigate much in this issue, for 2 reasons:
- the rrule code is more or less unchanged from D.Olfelts original implementation, and it is hard to read/understand and deprecated.  an approriate solution would IMHO be to just throw it away and use a state-of-the-art ICAL parsing Library.
- but, as I have stopped developing Plugins for WP and switched to Grav, I am not planning to do this.
Thus, I'm now closing this issue.

**Comment by norgey** [comment]
Thanks for the answer.
It's ok, in meantime i switched to "ICS Calendar" from room34 which offers similar possibilities. But i#m still using your WP-CalDav2ICS, which works great.

**Comment by wernerjoss** [comment]
ok, I also used to room34 ics calendar for awhile.
it is ok if you don't need more than one calendar, and it is actively developed.
wp-caldav2ics, which is my own creation from scratch, will be checked working with WP from time to time and eventually adapted if necessary, no guarantee, though 😄

**Comment by norgey** [comment]
The current version of room34 ics calendar supports multiple calendars... It is a little bit complicatet to use, but it works ([example](http://www.emk-reutlingen.de/herzlich-willkommen/calendar/)).
I switched to the github-version right now, befor i only know the wp-plugin.

**Comment by wernerjoss** [comment]
> The current version of room34 ics calendar supports multiple calendars... It is a little bit complicatet to use, but it works ([example](http://www.emk-reutlingen.de/herzlich-willkommen/calendar/)).

ok, I see, fine - so there is no more need for wp-ics-importer :smile: 

> I switched to the github-version right now, befor i only know the wp-plugin.

ok, let me know if/how it works for you
